name       : python-lxml
version    : 4.0.0
release    : 6
source     :
    - http://lxml.de/files/lxml-4.0.0.tgz : f7bc9f702500e205b1560d620f14015fec76dcd6f9e889a946a2ddcc3c344fd0
license    :
    - BSD-3-Clause
    - MIT
    - GPL-2.0
    - ZPL-2.0
component  : programming.python
summary    : Python 2 & 3 lxml Module
description: |
    lxml is the most feature-rich and easy-to-use library for processing XML and HTML in the Python language. It's also very fast and memory friendly, just so you know.
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(libxslt)
    - pkgconfig(python3)
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
check      : |
    export LC_ALL=en_US.utf8

    for py in "python" "python3" ; do
        PYTHON=${py} %make test
    done
