name       : python-lxml
version    : 3.8.0
release    : 4
source     :
    - http://lxml.de/files/lxml-3.8.0.tgz : 736f72be15caad8116891eb6aa4a078b590d231fdc63818c40c21624ac71db96
license    :
    - BSD-3-Clause
    - MIT
    - GPL-2.0
    - ZPL-2.0
component  : programming.python
summary    : Python 2 & 3 lxml Module
description: |
    lxml is the most feature-rich and easy-to-use library for processing XML and HTML in the Python language. It's also very fast and memory friendly, just so you know.
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(libxslt)
    - pkgconfig(python-3.5)
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
