name       : python-lxml
version    : 4.2.4
release    : 8
source     :
    - https://lxml.de/files/lxml-4.2.4.tgz : e2afbe403090f5893e254958d02875e0732975e73c4c0cdd33c1f009a61963ca
license    :
    - BSD-3-Clause
    - MIT
    - GPL-2.0-or-later
    - ZPL-2.0
component  : programming.python
summary    : Python 2 & 3 lxml Module
description: |
    lxml is the most feature-rich and easy-to-use library for processing XML and HTML in the Python language. It's also very fast and memory friendly, just so you know.
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(libxslt)
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    export LC_ALL=en_US.utf8

    pushd $PKG_BUILD_DIR/py2build
        python setup.py test
    popd

    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py test
    popd
