name       : python-lxml
version    : 3.4
release    : 1
source     :
    - http://lxml.de/files/lxml-3.4.4.tgz : b3d362bac471172747cda3513238f115cbd6c5f8b8e6319bf6a97a7892724099
license    :
    - BSD-3-Clause
    - MIT
    - GPL-2.0
    - ZPL-2.0
summary    : Python 2 & 3 lxml Module
description: |
    lxml is the most feature-rich and easy-to-use library for processing XML and HTML in the Python language. It's also very fast and memory friendly, just so you know.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.4)
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
